### ISSUE TITLE
One can upvote multiple times.

### ISSUE THREAD

**Issue by hifall** [iusvar/grav-plugin-thumb-ratings#4]
If one clicks the button multiple times, he can register upvote multiple times.

**Comment by iusvar** [comment]
Consider the [configuration parameters](https://github.com/iusvar/grav-plugin-thumb-ratings#config-defaults).

To avoid what you say you have to configure it as in the following image:

![image](https://user-images.githubusercontent.com/11983610/33241492-72dd6432-d2c6-11e7-937c-bc2652b5f256.png)

**Comment by hifall** [comment]
I see. That works.

Thanks!
