### ISSUE TITLE
Notify thumb-ratings to clear cache.

### ISSUE THREAD

**Issue by hifall** [iusvar/grav-plugin-thumb-ratings#5]
We are embedding Grav/thumb-ratings plugin in our system to manage articles. From time to time, our system will change an article's slug, and update the corresponding entry in data/thumbs.json for counters. However, I will have to manually call Grav's clear-cache command to clear the cache before the correct up/down numbers are shown.

This is because thumb-ratings tries to read from Grav's cache first in getVoteData. So my question is: is it possible to call thumb-ratings to clear the cache after we have changed an article's slug?

**Comment by iusvar** [comment]
If I did not understand, for some reason you use a procedure to change the items slug, even within thumbs.json.

As the thumbs-rating plugin tries to read first in the cache, you need to empty the cache to let you read the new thumbs.json modified by your procedure.

Is this your plugin built into Grav? I mean, did you create another plugin to make these changes?
In this case, it would be advisable to call up the command to clear the cache to the inoculation of your procedure.

Or is it an external procedure that you run out of the Grav environment without any possibility of automatic caching in the cache?

If so, I might think about modifying my plugin by adding an option that lets you use or not use the cache.

One more thing. If your site is online, can you provide the address?
